title: Hello Github Pages
author: Mohammad Faisal Afroz
email: faisalafroz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My hello world program for Github Pages.

# social links
twitter_username: iMDFaisal # DO NOT include the @ character, or else the build will fail!
github_username: FaisalAfroz # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
